version: '3.1'

services:
    flowise-staging:
        build:
            context: .
            dockerfile: Dockerfile # or ./docker/Dockerfile if that’s where your source-based Dockerfile is
        restart: always
        env_file:
            - ./docker/.env.staging
        ports:
            - '3001:3001'
        volumes:
            - ~/.flowise-staging:/root/.flowise
            - ./docker/staging.db:/usr/src/staging.db
        entrypoint: ['pnpm', 'start']
