services:
    flowise-prod:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - '3001:3001'
        volumes:
            - ~/.flowise-prod:/root/.flowise
        entrypoint: ['pnpm', 'start']
