services:
    flowise-prod:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        env_file:
            - ./docker/.env.production
        environment:
            - DATABASE_TYPE=postgres
            - DATABASE_HOST=${DATABASE_HOST}
            - DATABASE_PORT=${DATABASE_PORT}
            - DATABASE_USER=${DATABASE_USER}
            - DATABASE_PASSWORD=${DATABASE_PASSWORD}
            - DATABASE_NAME=${DATABASE_NAME}
        ports:
            - '3001:3001'
        volumes:
            - ~/.flowise-prod:/root/.flowise
        entrypoint: ['pnpm', 'start']
